# Generated by Django 2.0.2 on 2018-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='sliders')),
                ('title', models.CharField(max_length=24)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('button_title', models.CharField(blank=True, max_length=24)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
