# Generated by Django 2.0.2 on 2018-09-20 17:10

from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_name', models.CharField(default='', editable=False, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to='books')),
                ('purchase_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, validators=[learning.models.validate_rating])),
                ('review', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'ordering': ['-read_at', 'author', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url_title', models.CharField(default='', editable=False, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='courses')),
                ('page_url', models.URLField(blank=True)),
                ('summary_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=False)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('graduated_at', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, validators=[learning.models.validate_rating])),
                ('review', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['current', '-graduated_at', '-started_at', 'school', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True)),
                ('author', models.CharField(blank=True, max_length=140)),
                ('author_job_title', models.CharField(blank=True, default='', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'ordering': ['-created_at', 'author'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url_name', models.CharField(default='', editable=False, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='schools')),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
    ]
